# -*- coding: utf-8 -*-
"""Python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_HYy-sGOcpsjkSVg31in47pLmbMl5Rc8
"""

# Declare an integer variable
num1 = 5
num2 = 2.0
num3 = 1 + 2j

print(type(num1))
print(type(num2))
print(type(num3))

# Arithmatic operation
add = num1 + num2
print(add)

sub = num1 - num2
print(f"Subtraction: {num1} - {num2} = {sub}")

mul = num1 * num2
print(f"Multiplication: {num1} * {num2} = {mul}")

div = num1 / num2
print(f"Division: {num1} / {num2} = {div}")

my_variable = "string"
print(my_variable)

""" Factorial Calculator"""

n=int(input('Enter the number-'))

def fact(n):

    f = 1
    for i in range(1, n+1):
        f= f*i

    return f


a=5
result=fact(a)
print(result)

"""Leap year checker"""

year = int(input("Enter year : "))

if (year%4==0) and (year%400==0) :
    print(year,"is a leap year.")

elif (year%4==0) and (year%100!=0):
    print(year,"is a leap year.")
else:
    print(year,"is not a leap year.")

""" Palindrome Checker"""

a=input("Enter string:")
b=a[::-1]
if(a==b):
    print("Palindrom ")
else:
    print("Not Palindrome")